# -*- coding: utf-8 -*-
"""ADY_Proj_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJgg8S_I3gNL-3toz7DegJQ45U-cr38U
"""

# Commented out IPython magic to ensure Python compatibility.
# @title
# %pip install pandas numpy matplotlib seaborn plotly pymongo python-dotenv

# 📦 Import các thư viện cần thiết
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
from datetime import datetime, timedelta
import pymongo
from pymongo import MongoClient
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Cấu hình hiển thị
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("✅ Đã import thành công tất cả thư viện cần thiết!")
# 🔗 Kết nối MongoDB Atlas
def connect_to_mongodb():
    """Kết nối đến MongoDB Atlas"""
    try:
        # Lấy thông tin từ .env
        mongo_uri = os.getenv('MONGO_URI', 'mongodb+srv://thaian:thaian123@taxanalyses.qxevmke.mongodb.net/?retryWrites=true&w=majority&appName=TaxAnalyses')
        db_name = os.getenv('MONGO_DB_NAME', 'MolaDatabase')

        # Kết nối với timeout
        client = MongoClient(mongo_uri, serverSelectionTimeoutMS=5000)
        db = client[db_name]

        # Test connection
        client.admin.command('ping')
        print(f"✅ Kết nối thành công đến MongoDB Atlas!")
        print(f"📊 Database: {db_name}")

        # Liệt kê collections và thống kê
        collections = db.list_collection_names()
        print(f"📁 Collections có sẵn ({len(collections)}):")

        for coll_name in collections:
            count = db[coll_name].count_documents({})
            size = db.command("collStats", coll_name).get('size', 0)
            print(f"   • {coll_name}: {count:,} documents ({size/1024/1024:.2f} MB)")

        return client, db

    except Exception as e:
        print(f"❌ Lỗi kết nối: {e}")
        print("💡 Kiểm tra:")
        print("   - File .env có đúng MONGO_URI không?")
        print("   - Kết nối internet ổn định không?")
        print("   - MongoDB Atlas có cho phép IP hiện tại không?")
        return None, None

# Thực hiện kết nối
client, db = connect_to_mongodb()
# 📋 Phân tích cấu trúc database
def analyze_database_structure(db):
    """Phân tích cấu trúc và thống kê cơ bản của database"""
    print("🔍 PHÂN TÍCH CẤU TRÚC DATABASE")
    print("=" * 70)

    if db is None:
        print("❌ Không có kết nối database")
        return None

    structure_info = {}

    # Thứ tự ưu tiên collections (theo thiết kế hệ thống)
    collections_priority = ['invoices', 'invoice_items', 'invoice_analytics',
                           'HoaDonBanRa', 'HoaDonMuaVao']
    all_collections = db.list_collection_names()

    # Sắp xếp theo thứ tự ưu tiên
    sorted_collections = [c for c in collections_priority if c in all_collections]
    sorted_collections.extend([c for c in all_collections if c not in collections_priority])

    for collection_name in sorted_collections:
        collection = db[collection_name]

        # Đếm documents
        count = collection.count_documents({})

        if count == 0:
            print(f"\n📁 Collection: {collection_name} - ⚠️ TRỐNG")
            continue

        # Lấy sample document để xem cấu trúc
        sample = collection.find_one()

        # Thống kê collection
        coll_stats = db.command("collStats", collection_name)
        size_mb = coll_stats.get('size', 0) / 1024 / 1024

        # Lấy indexes
        indexes = collection.list_indexes()
        index_names = [idx['name'] for idx in indexes]

        structure_info[collection_name] = {
            'count': count,
            'size_mb': size_mb,
            'sample_fields': list(sample.keys()) if sample else [],
            'indexes': index_names,
            'sample_doc': sample
        }

        print(f"\n📁 Collection: {collection_name}")
        print(f"   📊 Số documents: {count:,}")
        print(f"   💾 Kích thước: {size_mb:.2f} MB")
        print(f"   🔧 Các fields: {', '.join(structure_info[collection_name]['sample_fields'][:15])}")
        print(f"   🔑 Indexes: {', '.join(index_names)}")

        # Thống kê theo thời gian nếu có trường date
        date_fields = ['issue_date', 'created_at', 'date', 'Ngày lập hóa đơn']
        date_field = None

        for field in date_fields:
            if field in sample:
                date_field = field
                break

        if date_field:
            try:
                # Tìm khoảng thời gian
                date_range = list(collection.aggregate([
                    {
                        "$match": {
                            date_field: {"$exists": True, "$ne": None}
                        }
                    },
                    {
                        "$group": {
                            "_id": None,
                            "min_date": {"$min": f"${date_field}"},
                            "max_date": {"$max": f"${date_field}"},
                            "count": {"$sum": 1}
                        }
                    }
                ]))

                if date_range and date_range[0]['count'] > 0:
                    min_date = date_range[0]['min_date']
                    max_date = date_range[0]['max_date']
                    print(f"   📅 Khoảng thời gian: {min_date} → {max_date}")

                    # Tính số ngày
                    if isinstance(min_date, str) and isinstance(max_date, str):
                        try:
                            min_dt = pd.to_datetime(min_date)
                            max_dt = pd.to_datetime(max_date)
                            days_diff = (max_dt - min_dt).days
                            print(f"   ⏱️  Thời gian: {days_diff} ngày")
                        except:
                            pass
            except Exception as e:
                print(f"   ⚠️  Không thể phân tích thời gian: {e}")

        # Hiển thị sample document structure (nested)
        print(f"   📋 Cấu trúc dữ liệu mẫu:")
        for key, value in list(sample.items())[:10]:
            value_type = type(value).__name__
            if isinstance(value, dict):
                print(f"      • {key}: {{object}} - {list(value.keys())[:5]}")
            elif isinstance(value, list):
                print(f"      • {key}: [array] - length: {len(value)}")
            else:
                print(f"      • {key}: {value_type}")

    return structure_info

# Phân tích cấu trúc
if db is not None:
    db_structure = analyze_database_structure(db)
else:
    print("❌ Không thể phân tích do lỗi kết nối")
# 🔄 Đọc dữ liệu từ các collections (PHIÊN BẢN TỐI ƯU)
def load_data_to_dataframes(db, limit=5000):
    """Đọc dữ liệu từ MongoDB và chuyển thành DataFrame"""
    dataframes = {}

    if db is None:
        print("❌ Database connection not available")
        return dataframes

    # Collection theo thiết kế hệ thống (ưu tiên collections mới)
    collections_info = {
        'invoices': {
            'description': 'Hóa đơn chính (cấu trúc mới)',
            'priority': 1,
            'nested_fields': ['seller', 'buyer', 'financial_summary', 'processing_info']
        },
        'invoice_items': {
            'description': 'Chi tiết sản phẩm/dịch vụ',
            'priority': 2,
            'nested_fields': []
        },
        'invoice_analytics': {
            'description': 'Phân tích tổng hợp (auto-generated)',
            'priority': 3,
            'nested_fields': []
        },
        'HoaDonBanRa': {
            'description': 'Hóa đơn bán ra (legacy/raw)',
            'priority': 4,
            'nested_fields': []
        },
        'HoaDonMuaVao': {
            'description': 'Hóa đơn mua vào (legacy/raw)',
            'priority': 5,
            'nested_fields': []
        }
    }

    # Sắp xếp theo priority
    sorted_collections = sorted(collections_info.items(), key=lambda x: x[1]['priority'])

    for collection_name, info in sorted_collections:
        try:
            if collection_name not in db.list_collection_names():
                print(f"⚠️  Collection '{collection_name}' không tồn tại")
                continue

            total_count = db[collection_name].count_documents({})

            if total_count == 0:
                print(f"\n📖 {info['description']} [{collection_name}] - TRỐNG")
                continue

            print(f"\n📖 Đang đọc: {info['description']} [{collection_name}]")
            print(f"   📊 Tổng: {total_count:,} documents")

            # Query với limit nếu cần
            if limit and total_count > limit:
                print(f"   ⚡ Giới hạn: {limit:,} documents (để tăng tốc)")
                cursor = db[collection_name].find({}).limit(limit)
            else:
                cursor = db[collection_name].find({})

            # Chuyển đổi sang DataFrame
            print(f"   ⏳ Đang tải dữ liệu...")
            data = list(cursor)

            if not data:
                print(f"   ⚠️  Không có dữ liệu")
                continue

            df = pd.DataFrame(data)

            # Xử lý ObjectId
            if '_id' in df.columns:
                df['_id'] = df['_id'].astype(str)

            # Xử lý nested fields (flatten) - CHỈ với invoices
            if collection_name == 'invoices':
                for nested_field in info['nested_fields']:
                    if nested_field in df.columns and df[nested_field].notna().any():
                        first_val = df[nested_field].dropna().iloc[0] if len(df[nested_field].dropna()) > 0 else None

                        if isinstance(first_val, dict):
                            try:
                                # Flatten nested dictionary
                                nested_df = pd.json_normalize(df[nested_field])
                                nested_df.columns = [f"{nested_field}.{col}" for col in nested_df.columns]
                                df = pd.concat([df, nested_df], axis=1)
                                print(f"   🔄 Đã flatten: {nested_field}")
                            except:
                                pass

            # Chuyển đổi date fields sang datetime (NHANH HƠN)
            date_fields = ['issue_date', 'created_at', 'updated_at', 'date', 'Ngày lập hóa đơn']

            for field in date_fields:
                if field in df.columns:
                    try:
                        df[field] = pd.to_datetime(df[field], errors='coerce')
                    except:
                        pass

            # Chuyển đổi numeric fields (NHANH HƠN)
            numeric_fields = ['Tổng tiền thanh toán', 'Tiền thuế', 'Thành tiền chưa thuế',
                            'Số lượng', 'Đơn giá', 'total_amount', 'tax_amount', 'subtotal']

            for field in numeric_fields:
                if field in df.columns:
                    try:
                        df[field] = pd.to_numeric(df[field], errors='coerce')
                    except:
                        pass

            dataframes[collection_name] = df

            # Thống kê nhanh
            print(f"   ✅ Đã tải: {len(df):,} rows × {len(df.columns)} columns")
            print(f"   💾 Memory: {df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB")

        except Exception as e:
            print(f"   ❌ Lỗi: {e}")

    # Tóm tắt
    print(f"\n{'='*70}")
    print(f"📊 TỔNG KẾT: {len(dataframes)} collections, {sum(len(df) for df in dataframes.values()):,} records")
    print(f"{'='*70}")

    return dataframes

# ⚡ ĐỌC DỮ LIỆU VỚI GIỚI HẠN (Nhanh hơn)
print("🚀 Bắt đầu đọc dữ liệu từ MongoDB Atlas...")
print("⚡ Sử dụng limit để tăng tốc phân tích\n")

# THAY ĐỔI Ở ĐÂY: Giới hạn 5000 records/collection để chạy nhanh
# Nếu muốn đọc TOÀN BỘ: dùng limit=None (sẽ chạy lâu hơn)
dfs = load_data_to_dataframes(db, limit=5000)  # ⚡ Giới hạn 5000 records

# 📈 Phân tích cơ bản từng DataFrame
def basic_analysis(dfs):
    """Phân tích cơ bản cho từng DataFrame"""

    for name, df in dfs.items():
        print(f"\n📊 PHÂN TÍCH CƠ BẢN: {name.upper()}")
        print("=" * 60)

        # Thông tin cơ bản
        print(f"🔢 Kích thước: {df.shape[0]:,} rows x {df.shape[1]} columns")
        print(f"💾 Memory usage: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

        # Kiểm tra missing values
        missing = df.isnull().sum()
        if missing.sum() > 0:
            print(f"\n⚠️ Missing values:")
            missing_pct = (missing / len(df) * 100).round(2)
            for col in missing[missing > 0].index:
                print(f"   {col}: {missing[col]:,} ({missing_pct[col]}%)")
        else:
            print("✅ Không có missing values")

        # Data types
        print(f"\n🏷️ Data types:")
        type_counts = df.dtypes.value_counts()
        for dtype, count in type_counts.items():
            print(f"   {dtype}: {count} columns")

        # Hiển thị sample data
        print(f"\n📋 Sample data (5 rows đầu):")
        display(df.head())

        # Nếu có cột số, hiển thị thống kê mô tả
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        if len(numeric_cols) > 0:
            print(f"\n📊 Thống kê mô tả (numeric columns):")
            display(df[numeric_cols].describe())

# Thực hiện phân tích cơ bản
if dfs:
    basic_analysis(dfs)
else:
    print("⚠️ Không có dữ liệu để phân tích")

#Trung bình doanh thu hóa đơn theo tháng
avg_months = dfs['invoice_analytics'].groupby('month')['total_revenue'].mean().reset_index()
display(avg_months)

# Vẽ biểu đồ cột
plt.figure(figsize=(15, 7))
sns.barplot(data=avg_months, x='month', y='total_revenue', color='skyblue')
plt.title('Doanh thu trung bình hóa đơn theo tháng')
plt.xlabel('Tháng')
plt.ylabel('Doanh thu trung bình')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

#Top sản phẩm/dịch vụ bán chạy nhất
top_items = dfs['invoice_items'].groupby('item_name')
display(top_items[['item_name', 'quantity']].sum('quantity').sort_values(by='quantity', ascending = False))

#Doanh thu và thuế theo người mua
top_revenue_tax_buyer = dfs['invoice_analytics'].groupby('buyer_name')[['total_revenue', 'total_tax']].sum().sort_values(by='total_revenue', ascending=False)
display(top_revenue_tax_buyer)

# Vẽ biểu đồ cột cho top 10 người mua
plt.figure(figsize=(15, 8))
top_revenue_tax_buyer.head(10).plot(kind='bar', y=['total_revenue', 'total_tax'], ax=plt.gca())
plt.title('Tổng doanh thu và thuế theo người mua (Top 10)')
plt.xlabel('Tên người mua')
plt.ylabel('Tổng giá trị')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Doanh thu trung bình theo trạng thái hóa đơn
avg_status = dfs['invoice_analytics'].groupby('invoice_status')['total_revenue'].mean().reset_index()
display(avg_status)

# Vẽ biểu đồ cột
plt.figure(figsize=(10, 6))
sns.barplot(data=avg_status, x='invoice_status', y='total_revenue', palette='viridis')
plt.title('Doanh thu trung bình theo trạng thái hóa đơn')
plt.xlabel('Trạng thái hóa đơn')
plt.ylabel('Doanh thu trung bình')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

#Doanh thu theo tháng và hình thức thanh toán
top_revenue_month = dfs['invoice_analytics'].groupby(['month', 'payment_method'])['total_revenue'].sum().reset_index()
display(top_revenue_month)

# Vẽ biểu đồ cột
plt.figure(figsize=(15, 7))
sns.barplot(data=top_revenue_month, x='month', y='total_revenue', hue='payment_method')
plt.title('Doanh thu theo tháng và hình thức thanh toán')
plt.xlabel('Tháng')
plt.ylabel('Tổng doanh thu')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()