# -*- coding: utf-8 -*-
"""ADY_Proj_SQLite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjgUhFPcdVo178RfwIz8BOQW1VTN98Rl
"""

# Commented out IPython magic to ensure Python compatibility.
# 📚 Import Libraries
# %pip install pymongo
import os
import sys
import sqlite3
import json
from datetime import datetime
from dotenv import load_dotenv
import pymongo
from pymongo import MongoClient
from bson import ObjectId
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

load_dotenv()

print("✅ Libraries imported successfully!")
print(f"📦 Pandas: {pd.__version__}")
print(f"📦 SQLite: {sqlite3.sqlite_version}")
# 🔗 Connect to MongoDB Atlas
def connect_mongodb_atlas():
    """Connect to MongoDB Atlas with SSL support"""
    try:
        mongo_uri = os.getenv('MONGO_URI', 'mongodb+srv://thaian:thaian123@taxanalyses.qxevmke.mongodb.net/?retryWrites=true&w=majority&appName=TaxAnalyses')
        db_name = os.getenv('MONGO_DB_NAME', 'MolaDatabase')

        print("🔧 Connecting to MongoDB Atlas...")

        client = MongoClient(
            mongo_uri,
            tls=True,
            tlsAllowInvalidCertificates=True,
            tlsAllowInvalidHostnames=True,
            serverSelectionTimeoutMS=60000
        )

        db = client[db_name]
        client.admin.command('ping')

        print(f"✅ Connected to MongoDB Atlas!")
        print(f"📊 Database: {db_name}")
        print(f"📁 Collections: {db.list_collection_names()}")

        return client, db

    except Exception as e:
        print(f"❌ Connection error: {e}")
        return None, None

# Connect
client, db = connect_mongodb_atlas()
# 🔄 SMART MONGODB TO SQLITE CONVERTER
def convert_to_sqlite(db, output_db='tax_invoices.db'):
    """
    Convert MongoDB collections to SQLite with smart flattening
    """
    print("\n" + "="*80)
    print("🔄 MONGODB → SQLITE CONVERSION")
    print("="*80)

    # Remove existing database
    if os.path.exists(output_db):
        os.remove(output_db)
        print(f"🗑️  Removed existing: {output_db}")

    # Create SQLite connection
    conn = sqlite3.connect(output_db)
    cursor = conn.cursor()

    print(f"✅ Created: {output_db}\n")

    # ====================
    # 1️⃣ INVOICES TABLE
    # ====================
    print("📦 Processing: invoices")
    invoices = list(db.invoices.find())

    invoices_flat = []
    for inv in invoices:
        flat = {
            '_id': str(inv['_id']),
            'invoice_number': inv.get('invoice_number'),
            'template_code': inv.get('template_code'),
            'symbol': inv.get('symbol'),
            'issue_date': inv.get('issue_date'),
            'seller_signature_date': inv.get('seller_signature_date'),
            'tax_office_signature_date': inv.get('tax_office_signature_date'),

            # Flatten seller
            'seller_name': inv.get('seller', {}).get('name'),
            'seller_tax_code': inv.get('seller', {}).get('tax_code'),
            'seller_address': inv.get('seller', {}).get('address'),

            # Flatten buyer
            'buyer_name': inv.get('buyer', {}).get('name'),
            'buyer_tax_code': inv.get('buyer', {}).get('tax_code'),
            'buyer_address': inv.get('buyer', {}).get('address'),

            # Flatten financial_summary
            'subtotal': inv.get('financial_summary', {}).get('subtotal_before_tax'),
            'discount': inv.get('financial_summary', {}).get('total_discount'),
            'tax_amount': inv.get('financial_summary', {}).get('total_tax'),
            'fee_amount': inv.get('financial_summary', {}).get('total_fees'),
            'total_amount': inv.get('financial_summary', {}).get('total_amount'),
            'currency': inv.get('financial_summary', {}).get('currency'),
            'exchange_rate': inv.get('financial_summary', {}).get('exchange_rate'),

            # Flatten processing_info
            'status': inv.get('processing_info', {}).get('status'),
            'verification_result': inv.get('processing_info', {}).get('verification_result'),
            'tax_office_code': inv.get('processing_info', {}).get('tax_office_code'),
            'lookup_code': inv.get('processing_info', {}).get('lookup_code'),
            'payment_method': inv.get('processing_info', {}).get('payment_method'),
            'created_at': inv.get('processing_info', {}).get('created_at'),
            'updated_at': inv.get('processing_info', {}).get('updated_at'),
            'username': inv.get('processing_info', {}).get('username'),
            'item_count': inv.get('processing_info', {}).get('item_count'),
            'has_products_details': inv.get('processing_info', {}).get('has_products_details'),
        }
        invoices_flat.append(flat)

    df_invoices = pd.DataFrame(invoices_flat)
    df_invoices.to_sql('invoices', conn, if_exists='replace', index=False)
    print(f"   ✅ Created: invoices ({len(df_invoices)} rows, {len(df_invoices.columns)} columns)")

    # ====================
    # 2️⃣ INVOICE_ITEMS TABLE
    # ====================
    print("📦 Processing: invoice_items")
    items = list(db.invoice_items.find())

    items_flat = []
    for item in items:
        flat = {
            '_id': str(item['_id']),
            'invoice_id': str(item.get('invoice_id')),
            'invoice_unique_key': item.get('invoice_unique_key'),
            'item_code': item.get('item_code'),
            'item_name': item.get('item_name'),
            'unit': item.get('unit'),
            'quantity': item.get('quantity'),
            'unit_price': item.get('unit_price'),
            'discount': item.get('discount'),
            'subtotal': item.get('subtotal'),
            'tax_rate': item.get('tax_rate'),
            'tax_amount': item.get('tax_amount'),
            'tax_type': item.get('tax_type'),
            'item_type': item.get('item_type'),
            'item_type_display': item.get('item_type_display'),
            'notes_1': item.get('notes_1'),
            'notes_2': item.get('notes_2'),
            'expiry_date': item.get('expiry_date'),
            'batch_number': item.get('batch_number'),
            'created_at': item.get('created_at'),
            'sequence': item.get('sequence'),
        }
        items_flat.append(flat)

    df_items = pd.DataFrame(items_flat)
    df_items.to_sql('invoice_items', conn, if_exists='replace', index=False)
    print(f"   ✅ Created: invoice_items ({len(df_items)} rows, {len(df_items.columns)} columns)")

    # ====================
    # 3️⃣ INVOICE_ANALYTICS TABLE
    # ====================
    print("📦 Processing: invoice_analytics")
    analytics = list(db.invoice_analytics.find())

    analytics_flat = []
    for ana in analytics:
        flat = {
            '_id': str(ana['_id']),
            'date': ana.get('date'),
            'seller_tax_code': ana.get('seller_tax_code'),
            'buyer_tax_code': ana.get('buyer_tax_code'),
            'month': ana.get('month'),
            'year': ana.get('year'),
            'seller_name': ana.get('seller_name'),
            'buyer_name': ana.get('buyer_name'),
            'total_invoices': ana.get('total_invoices'),
            'total_items': ana.get('total_items'),
            'total_revenue': ana.get('total_revenue'),
            'total_tax': ana.get('total_tax'),
            'payment_method': ana.get('payment_method'),
            'invoice_status': ana.get('invoice_status'),
            'updated_at': ana.get('updated_at'),
        }
        analytics_flat.append(flat)

    df_analytics = pd.DataFrame(analytics_flat)
    df_analytics.to_sql('invoice_analytics', conn, if_exists='replace', index=False)
    print(f"   ✅ Created: invoice_analytics ({len(df_analytics)} rows, {len(df_analytics.columns)} columns)")

    # ====================
    # CREATE INDEXES
    # ====================
    print("\n🔍 Creating indexes...")

    cursor.execute("CREATE INDEX IF NOT EXISTS idx_invoices_id ON invoices(_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_invoices_issue_date ON invoices(issue_date)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_invoices_buyer_tax ON invoices(buyer_tax_code)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_invoices_seller_tax ON invoices(seller_tax_code)")

    cursor.execute("CREATE INDEX IF NOT EXISTS idx_items_invoice_id ON invoice_items(invoice_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_items_item_name ON invoice_items(item_name)")

    cursor.execute("CREATE INDEX IF NOT EXISTS idx_analytics_month ON invoice_analytics(month)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_analytics_year ON invoice_analytics(year)")

    print("   ✅ Indexes created")

    conn.commit()

    # ====================
    # SUMMARY
    # ====================
    print("\n" + "="*80)
    print("📊 CONVERSION SUMMARY")
    print("="*80)

    total_rows = len(df_invoices) + len(df_items) + len(df_analytics)
    file_size = os.path.getsize(output_db) / 1024**2

    print(f"\n💾 Database: {output_db}")
    print(f"📏 File size: {file_size:.2f} MB")
    print(f"📊 Total rows: {total_rows:,}")
    print(f"\n📋 Tables:")
    print(f"   1. invoices: {len(df_invoices)} rows, {len(df_invoices.columns)} columns")
    print(f"   2. invoice_items: {len(df_items)} rows, {len(df_items.columns)} columns")
    print(f"   3. invoice_analytics: {len(df_analytics)} rows, {len(df_analytics.columns)} columns")

    conn.close()

    return output_db

# Execute conversion
if client is not None and db is not None:
    db_path = convert_to_sqlite(db)
    print("\n🎉 CONVERSION COMPLETED!")
    print(f"💡 SQLite database ready: {db_path}")
else:
    print("❌ Cannot convert - no MongoDB connection")
# 🔗 Connect to SQLite
def run_sql_query(db_path, query, description=""):
    """Execute SQL query and display results"""
    print("\n" + "="*90)
    if description:
        print(f"📊 {description}")
    print("="*90)
    print(f"\n🔍 SQL:")
    print(query)
    print("\n📋 Results:")

    try:
        conn = sqlite3.connect(db_path)
        df = pd.read_sql_query(query, conn)
        conn.close()

        if len(df) > 0:
            print(df.to_string(index=False))
            print(f"\n✅ {len(df)} rows returned")
        else:
            print("📭 No results")

        return df
    except Exception as e:
        print(f"❌ Query failed: {e}")
        return pd.DataFrame()

print("✅ Query function ready")

"""## 📐 ER DIAGRAM VISUALIZATION

Visualize database schema với relationships giữa các bảng
"""

# 📊 Install required packages for ER diagram
# Uncomment dòng dưới nếu chưa cài đặt:
# !pip install graphviz matplotlib

print("✅ Ready to generate ER diagram")

# 🎨 METHOD 1: TEXT-BASED ER DIAGRAM (Simple & Fast)
def show_database_schema(db_path):
    """Display database schema in text format"""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    print("\n" + "="*90)
    print("📊 SQLITE DATABASE SCHEMA")
    print("="*90)

    # Get all tables
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
    tables = cursor.fetchall()

    for (table_name,) in tables:
        print(f"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        print(f"┃ 📋 TABLE: {table_name}")
        print(f"┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

        # Get table info
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = cursor.fetchall()

        print(f"{'Column':<30} {'Type':<15} {'Nullable':<10} {'Key':<10}")
        print("-" * 70)

        for col in columns:
            col_id, name, col_type, not_null, default, pk = col
            nullable = "NO" if not_null else "YES"
            key = "PK" if pk else ""
            print(f"{name:<30} {col_type:<15} {nullable:<10} {key:<10}")

        # Get indexes
        cursor.execute(f"PRAGMA index_list({table_name})")
        indexes = cursor.fetchall()
        if indexes:
            print(f"\n  🔍 Indexes:")
            for idx in indexes:
                print(f"     • {idx[1]}")

    # Show relationships
    print("\n" + "="*90)
    print("🔗 RELATIONSHIPS")
    print("="*90)
    print("\ninvoice_items.invoice_id → invoices._id")
    print("   (One invoice has many items)")
    print("\ninvoice_analytics.seller_tax_code → invoices.seller_tax_code")
    print("invoice_analytics.buyer_tax_code → invoices.buyer_tax_code")
    print("   (Analytics aggregated from invoices)")

    conn.close()

# Execute
if 'db_path' in locals():
    show_database_schema(db_path)

#Trung bình doanh thu hóa đơn theo tháng
query_avg_monthly_revenue = """
SELECT
    month  ,
    AVG(total_revenue) as avg_monthly_revenue
FROM invoice_analytics
WHERE total_revenue IS NOT NULL
GROUP BY month
"""
if 'db_path' in locals():
    avg_monthly_revenue_df = run_sql_query(db_path, query_avg_monthly_revenue,
                                        "TRUNG BÌNH DOANH THU HÓA ĐƠN THEO THÁNG")

#Top sản phẩm/dịch vụ bán chạy nhất
query_top_selling_products = """
SELECT
    invoice_id,
    count(*) as item_count
from invoice_items
GROUP BY invoice_id
ORDER BY item_count DESC
LIMIT 10;
"""
if 'db_path' in locals():
    top_selling_products_df = run_sql_query(db_path, query_top_selling_products,
                                        "TOP SẢN PHẨM/DỊCH VỤ BÁN CHẠY NHẤT")

#Doanh thu và thuế theo người mua
query_revenue_tax_by_buyer = """
SELECT
    buyer_name,
    sum(total_revenue) as total_revenue,
    sum(total_tax) as total_tax
from invoice_analytics
WHERE total_revenue IS NOT NULL
GROUP BY buyer_name
order by total_revenue desc
"""
if 'db_path' in locals():
    revenue_tax_by_buyer_df = run_sql_query(db_path, query_revenue_tax_by_buyer,
                                        "DOANH THU VÀ THUẾ THEO NGƯỜI MUA")

#Doanh thu trung bình theo trạng thái hóa đơn
query_avg_revenue_by_status = """
SELECT
    invoice_status,
    avg(total_revenue) as avg_revenue
FROM invoice_analytics
GROUP BY invoice_status
"""
if 'db_path' in locals():
    avg_revenue_by_status_df = run_sql_query(db_path, query_avg_revenue_by_status,
                                        "DOANH THU TRUNG BÌNH THEO TRẠNG THÁI HÓA ĐƠN")

#Doanh thu theo tháng và hình thức thanh toán
query_revenue_by_month_payment = """
SELECT
    month,
    payment_method,
    SUM(total_revenue) as total_revenue,
    SUM(total_invoices) as total_invoices
from invoice_analytics
WHERE total_revenue IS NOT NULL
GROUP BY month, payment_method
ORDER BY month DESC, total_revenue DESC
"""
if 'db_path' in locals():
    revenue_by_month_payment_df = run_sql_query(db_path, query_revenue_by_month_payment,
                                        "DOANH THU THEO THÁNG VÀ HÌNH THỨC THANH TOÁN")